export const getTitle = (val) => {
    return labels[val];
}

const labels = {
    ADMIN_DASHBOARD: "ADMIN DASHBOARD",
    LOW: "Low",
    HIGH: "High",
    MEDIUM: "Medium",
    ALL: "All",
    ADD_TASK: "Add Task",
    LOG_IN: "Logged in as: ",
    LOGOUT: "Logout",
    ADD_NEW_PROJECT: "Add New Project",
    PROJECTS: "Projects",
    LOADING: "Loading..",
    ERROR: "Error: ",
    ASSIGNED_MANAGER: "Assigned Manager: ",
    DESCRIPTION: "Description: ",
    DUE_DATE: "Due Date: ",
    LOGGED_IN_AS: "Logged in as: ",
    SHOW_ANALYTICS: "Show Analytics",
    USER_DASHBOARD: "USER DASHBOARD",
    ASSIGNED_TASKS: "Assigned Tasks",
    ATTACHMENT: "Attachment: ",
    PRIORITY: "Priority: ",
    DUE_DATE_ALERT: "Due date has passed!",
    DEPENDENCIES: "Dependencies: ",
    NOTIFICATIONS: "Notifications",
    MARK_ALL_READ: "Mark All as Read",
    NO_NOTIFICATIONS: "No notifications",
    MARK_READ: "Mark as Read",
    MANAGER_DASHBOARD: "MANAGER DASHBOARD",
    EDIT_TASK: "Edit Task",
    TITLE: "Title",
    ASSIGNED_TO: "Assigned To: ",
    SELECT_USER: "Select User",
    CANCEL: "Cancel",
    SAVE: "Save",
    PROJECT_ANALYTICS: "Project Analytics",
    CLOSE: "Close",
    COMPLETION_PERCENTAGE: "Completion Percentage",
    TASKS_BY_STATUS: "Tasks by Status",
    TASKS_BY_PRIORITY: "Tasks by Priority",
    OPTIONAL: "(Optional)",
    NO_TASK_AVAILABLE: "NO tasks available",
    ADD: "Add",
    ADD_PROJECT: "Add Project",
    PROJECT_NAME: "Project Name",
    COMMENTS: "Comments",
    NO_COMMENTS: "No comments yet",
    ACTIVITY_LOG: "Activity Log",
    PERFORMED: "performed: ",
    NO_ACTIVITY_LOGS: "No activity logs yet",
    EDIT_PROJECT: "Edit Project",
    NAME: "Name",
    SELECT_MANAGER: "Select Manager",
    LOGIN: "Login",
    NO_ACCOUNT: "Don't have an account?",
    SIGNUP: "Signup",
    ROLE: "Role",
    USER: "User",
    MANAGER: "Manager",
    SIGNUP_SUCCESS: "Signup successful! Redirecting...",
    HAVE_ACCOUNT: "Already have an account?",
    FETCH_COLUMNS: "FETCH_COLUMNS",
    ADD_COLUMN: "ADD_COLUMN",

}